using System.Text.Json.Serialization;

namespace DbPostPatcher.Patching;

/// <summary>
///     patches.enabled.json. "available" is engine-maintained - PatchLoaderMod rewrites it on
///     every boot to list every *.json currently under patches/, so the file is always a
///     complete, up-to-date menu of what can be turned on. "enabled" is yours - the engine never
///     changes it, only reads it.
/// </summary>
public sealed class EnabledPatchesConfig
{
    [JsonPropertyName("_comment")]
    public string Comment { get; init; } =
        "'available' is regenerated by the mod on every server boot - edit 'enabled' to turn patches on/off, don't hand-edit 'available'.";

    [JsonPropertyName("available")]
    public List<string> Available { get; init; } = [];

    [JsonPropertyName("enabled")]
    public List<string> Enabled { get; init; } = [];
}
